language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install pep8 pylint
script:
  - pep8 --exclude cast_channel_pb2.py pychromecast
  - pylint pychromecast
